stripe_secret_key: 'sk_test_51KGpPCC0xc9sAvNFzM5aLBFD3O6eg67Pom0OA2roxfV9riJinkVgEwFspBGsc5QUqkmIDGcqzmddQrC8Lyltv7DR00FtLonETJ'
stripe_publishable_key: 'pk_test_51KGpPCC0xc9sAvNFjgmwDef9I6MfDyNWUA5OnniuhczkYDpyrx29zisF65ubFS3dgyVgbQU631im0XrYvUbCgWOp00Y8fiQAB8'
